name: Update Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Delete existing tag
        run: |
          git tag -d dev
          git push origin :refs/tags/dev

      - name: Create new tag
        run: |
          git tag dev
          git push origin dev

      - name: Create or update GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: dev
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
