name: Update Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Verify current commit
        run: |
          echo "Current commit:"
          git log -1

      - name: Delete existing tag
        run: |
          git tag -d dev || true
          git push origin :refs/tags/dev || true

      - name: Verify tag deletion
        run: |
          git tag -l

      - name: Create new tag
        run: |
          git tag dev
          git push origin dev

      - name: Verify new tag creation
        run: |
          git tag -l

      - name: Create or update GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: dev
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
